services:
  grafana:
    image: "grafana/grafana:${GRAFANA_VERSION:-latest}"
    ports:
      - "${GRAFANA_PORT:-3000}:3000"
    volumes:
      - "${PWD:-.}/grafana:/var/lib/grafana"
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD:-admin}
